variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: localhost
  DOCKER_TLS_CERTDIR: ""
  TAG_FOR_IMAGES: $CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA

include:
  - project: 'gitlab-templates/ci-templates/java/gradle'
    file: 'gitlab-ci-template.yml'
  - project: 'gitlab-templates/ci-templates/build/docker'
    file: 'gitlab-ci-template.yml'  

stages:
  - build
 # - test
  - pushImage
 # - deploy
  - tfgcp
  - deployGCP

build:
  stage: build
  image: gradle:6.0.1-jdk8
  extends: .gradle_java_build
  tags:
    - runnerk8s

.test:
  stage: test
  script:
    - gradle test

pushImage:
  stage: pushImage
  extends: .docker_image_creation
  tags:
    - runnerk8s
  before_script:
    - docker login $URL_REGISTRY -u $USER -p $TOKEN
  script:
    - echo $DOCKER_HOST
    - echo $TAG_FOR_IMAGES
    - docker info
    - docker build -t $USER/$APP_NAME:$TAG_FOR_IMAGES . 
    - docker push $USER/$APP_NAME:$TAG_FOR_IMAGES

.deployMaster:
  stage: deploy
  image: ubuntu:xenial
  tags:
    - runnerk8s
  before_script:
    - apt-get update
    - apt-get install -y cl-base64
    - apt-get install -y openssh-client
    - mkdir ~/.ssh
    - echo $SSH_PRIVATE_KEY | base64 -d > $URL_KEY
    - chmod 600 $URL_KEY
  script:
    - scp -i $URL_KEY -o $KNOWN_HOST_FILE -o $KEY_CHECKING -o ConnectTimeout=10 deployEnv/deployMaster.sh $AWS_HOST:/tmp/
    - ssh -i $URL_KEY -o $KNOWN_HOST_FILE -o $KEY_CHECKING -o ConnectTimeout=10 $AWS_HOST "/tmp/deployMaster.sh $USER $APP_NAME $TAG_FOR_IMAGES"
  only:
    - master

.deployDev:
  stage: deploy
  image: ubuntu:xenial
  tags:
    - runnerk8s
  before_script:
    - apt-get update
    - apt-get install -y cl-base64
    - apt-get install -y openssh-client
    - mkdir ~/.ssh
    - echo $SSH_PRIVATE_KEY | base64 -d > $URL_KEY
    - chmod 600 $URL_KEY
  script:
    - scp -i $URL_KEY -o $KNOWN_HOST_FILE -o $KEY_CHECKING -o ConnectTimeout=10 deployEnv/deployDev.sh $AWS_HOST:/tmp/
    - ssh -i $URL_KEY -o $KNOWN_HOST_FILE -o $KEY_CHECKING -o ConnectTimeout=10 $AWS_HOST "/tmp/deployDev.sh $USER $APP_NAME $TAG_FOR_IMAGES"
  only:
    - develop   

.deployQA:
  stage: deploy
  image: ubuntu:xenial
  tags:
    - runnerk8s
  before_script:
    - apt-get update
    - apt-get install -y cl-base64
    - apt-get install -y openssh-client
    - mkdir ~/.ssh
    - echo $SSH_PRIVATE_KEY | base64 -d > $URL_KEY
    - chmod 600 $URL_KEY
  script:
    - scp -i $URL_KEY -o $KNOWN_HOST_FILE -o $KEY_CHECKING -o ConnectTimeout=10 deployEnv/deployQA.sh $AWS_HOST:/tmp/
    - ssh -i $URL_KEY -o $KNOWN_HOST_FILE -o $KEY_CHECKING -o ConnectTimeout=10 $AWS_HOST "/tmp/deployQA.sh $USER $APP_NAME $TAG_FOR_IMAGES"
  only:
    - qa

.deploy:
  stage: deploy
  image: ubuntu:xenial
  tags:
    - runnerk8s
  before_script:
    - apt-get update
    - apt-get install -y cl-base64
    - apt-get install -y openssh-client
    - mkdir ~/.ssh
    - echo $SSH_PRIVATE_KEY | base64 -d > $URL_KEY
    - chmod 600 $URL_KEY
  script:
    - scp -i $URL_KEY -o $KNOWN_HOST_FILE -o $KEY_CHECKING -o ConnectTimeout=10 deployEnv/deploy.sh $AWS_HOST:/tmp/
    - ssh -i $URL_KEY -o $KNOWN_HOST_FILE -o $KEY_CHECKING -o ConnectTimeout=10 $AWS_HOST "/tmp/deploy.sh $USER $APP_NAME $TAG_FOR_IMAGES"

tfgcp:
  stage: tfgcp
  image: hashicorp/terraform
  tags:
    - runnerk8s
  before_script:
    - echo "$SERVICE_ACCOUNT_KEY" > gke-token.json
    - export GOOGLE_APPLICATION_CREDENTIALS=gke-token.json
  script:
    - terraform init
  #  - terraform plan -o "plan.out"
    - terraform apply -auto-approve #plan.out


deployGCP:
  stage: deployGCP
  image: google/cloud-sdk:light
  tags:
    - runnerk8s
  only:
    - developDevOps
  script:
    - echo "$SERVICE_ACCOUNT_KEY" > gke-token.json
    - gcloud auth activate-service-account --key-file=gke-token.json
    - gcloud config set project prueba-gke-267214
    - gcloud config set container/cluster k8s-test
    - gcloud config set compute/zone us-central1-a
    - gcloud container clusters get-credentials k8s-test --zone us-central1-a
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
   # - ./kubectl create secret generic registry.hub.docker --from-literal=Docker_User=$"USER" --from-literal=Docker_Password=$"TOKEN" --dry-run -o yaml | kubectl apply -f -
    - ./kubectl apply -f 5award-namespace.yml
    - echo $TAG_FOR_IMAGES
    - ENV_NEW=$(cat deployment-app.yml | sed "s/{{imagen}}/$TAG_FOR_IMAGES/g")
    - echo "$ENV_NEW"
    - echo "$ENV_NEW" > deployment-app.yaml
    - ./kubectl apply -f deployment-app.yaml -n default
    - ./kubectl apply -f service-app.yaml   
   # - ./kubectl get nodes -o wide





