variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://192.168.65.1
  DOCKER_TLS_CERTDIR: ""

include:
  - project: 'gitlab-templates/ci-templates/java/gradle'
    file: 'gitlab-ci-template.yml'
  - project: 'gitlab-templates/ci-templates/build/docker'
    file: 'gitlab-ci-template.yml'  

stages:
  - build
  - test
  - pushImage
  - deploy

build:
  stage: build
  image: gradle:alpine
  extends: .gradle_java_build
  tags:
    - docker

.test:
  stage: test
  script:
    - gradle test

pushImage:
  stage: pushImage
  extends: .docker_image_creation
  tags:
    - docker
  before_script:
    - docker login $URL_REGISTRY -u $USER -p $TOKEN
  script:
    - docker build -t $APP_NAME:$CI_COMMIT_SHORT_SHA . 
    - docker push $USER/$APP_NAME:$CI_COMMIT_SHORT_SHA

.deployInAws:
  stage: deploy
  script:
    - hol