variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://192.168.65.1
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - test
  - pushImage
  - deploy

build:
  stage: build
  image: gradle:alpine
  tags:
    - docker
  script:
    - gradle build -x test
  artifacts:
    paths:
      - build/libs/*.jar  

.test:
  stage: test
  script:
    - gradle test

pushImage:
  stage: pushImage
  image: docker:19.03.5
  services:
    - docker:19.03.5-dind
  tags:
    - docker
  before_script:
    - echo $URL_REGISTRY
    - echo $USER
    - echo $TOKEN
    - docker login $URL_REGISTRY -u $USER -p $TOKEN
  script:
    - docker build -t $APP_NAME:$CI_COMMIT_SHORT_SHA . 
    - docker push $USER/$APP_NAME:$CI_COMMIT_SHORT_SHA

.deployInAws:
  stage: deploy
  script:
    - hola