image: ubuntu:xenial

stages:
  - build
  - test
  - pushImage
  - deploy

build:
  stage: build
  image: gradle:alpine
  tags:
    - docker
  script:
    - gradle build -x test

.test:
  stage: test
  script:
    - gradle test

pushImage:
  stage: pushImage
  image: docker:stable
  tags:
    - docker
  before_script:
    - docker login $URL_REGISTRY -u $USER -p $TOKEN
  script:
    - docker build -t $APP_NAME:$NUMBER_RANDOM .
    - docker push $USER/$APP_NAME:$NUMBER_RANDOM

.deployInAws:
  stage: deploy
  script:
    - hola