kind: Deployment
apiVersion: apps/v1
metadata:
  name: "{{deploy-name}}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{label}}"
  template:
    metadata:
      labels:
        app: "{{label}}"
    spec:
      containers:
      - name: "{{image-for-name}}"
        image: '"{{name-image}}":{{imagen}}'
        ports:
        - containerPort: 8080                 
