apiVersion: v1
kind: Service
metadata:
  name: {{name-service}}-service
  namespace: build-gitlab-namespace-5awards
spec:
  selector:
    app: {{backend-app}}
  ports:
  - port: {{PORT}}
    targetPort: {{TARGET_PORT}}
